version: "3.0"
services: 
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD={0}
    volumes:
    - ./data:/var/opt/mssql/data
    ports:
    - '1433:1433'

  travel-web:
    image: travel-image
    environment:
    - ConnectionStrings__DefaultConnection=Server=mssql;Database=TravelBooking;User Id=sa;Password={0}
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - '8080:80'